export const ACTION = {
    SET_PRODUCT: "SET_PRODUCT",
    CREATE_PRODUCT: "CREATE_PRODUCT",
    UPDATE_PRODUCT: "UPDATE_PRODUCT",
    DELETE_PRODUCT: "DELETE_PRODUCT",

    SET_CUSTOMNER: "SET_CUSTOMER",
    CREATE_CUSTOMER: "CREATE_CUSTOMER",
    UPDATE_CUSTOMER: "UPDATE_CUSTOMER",
    DELETE_CUSTOMER: "DELETE_CUSTOMER",

    ADD_CART: "ADD_CART",
    SET_CART: "SET_CART",
    DELETE_CART: "DELETE_CART",
    INCREASE_PRODUCT: "INCREASE_PRODUCT",
    DECREASE_PRODUCT: "DECREASE_PRODUCT"
};